export const INITIAL_STATE = {
  notes: {
    categories: {
      byId: {
        1: {
          id: 1,
          name: "Table of contents",
          childPageIds: [1, 4],
        },
        // 2: {
        //   id: 2,
        //   name: "Russian",
        //   childPageIds: [5],
        // },
      },
      allIds: [1, 2],
    },
    selectedNoteId: 1,
    byId: {
      1: {
        id: 1,
        title: "Basic grammar",
        content: "This is some placeholder content!",
        categoryId: 1,
        childPageIds: [2, 3],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      2: {
        id: 2,
        title: "Present simple",
        content: "Try to add some more text if you want to play with it",
        parentId: 1,
        categoryId: 1,
        childPageIds: [],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      3: {
        id: 3,
        title: "Present continuous",
        parentId: 1,
        categoryId: 1,
        childPageIds: [6, 7],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      4: {
        id: 4,
        title: "Vocabulary",
        categoryId: 1,
        childPageIds: [8],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      5: {
        id: 5,
        title: "Basic grammar",
        content: "In russian there is no basic grammar!",
        categoryId: 2,
        childPageIds: [],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      6: {
        id: 6,
        title: "Examples",
        content: "Some examples",
        parentId: 3,
        categoryId: 1,
        childPageIds: [9],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      7: {
        id: 7,
        title: "Exercises",
        content: "Some exercises",
        parentId: 3,
        categoryId: 1,
        childPageIds: [],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      8: {
        id: 8,
        title: "Nice to know words",
        content: "Words",
        parentId: 4,
        categoryId: 2,
        childPageIds: [],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      9: {
        id: 9,
        title: "Long explanatory exaple caption",
        content: "Words",
        parentId: 6,
        categoryId: 1,
        childPageIds: [10],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
      10: {
        id: 10,
        title: "Long explanatory exaple caption 2",
        content: "Words",
        parentId: 9,
        categoryId: 1,
        childPageIds: [],
        isExpanded: false,
        isTitleFresh: false,
        isContentFresh: false,
      },
    },
    allIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
};
