export const INITIAL_STATE_EMPTY = {
  notes: {
    isNoteMovementLoading: false,
    isNotesLoaded: false,
    isCategoriesLoaded: false,
    categories: {
      byId: {},
    },
    tree: {
      rootId: "root",
      items: {
        root: {
          id: "root",
          children: [],
          hasChildren: false,
          isExpanded: false,
        },
      },
    },
  },
};

export const INITIAL_STATE_TREE = {
  notes: {
    isNoteMovementLoading: false,
    isNotesLoaded: true,
    isCategoriesLoaded: true,
    categories: {
      byId: {
        "category-1": {
          id: "category-1",
          caption: "Languages",
        },
        "category-2": {
          id: "category-2",
          caption: "Task list",
        },
      },
    },
    tree: {
      rootId: "root",
      items: {
        root: {
          id: "root",
          children: ["note-1", "note-2", "note-10"],
          hasChildren: true,
          isExpanded: false,
        },
        "note-1": {
          id: "note-1",
          children: ["note-3", "note-4", "note-5", "note-6"],
          hasChildren: true,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "root",
            title: "Parent 1",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-2": {
          id: "note-2",
          children: ["note-7", "note-8", "note-9"],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "root",
            title: "Parent 2",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-3": {
          id: "note-3",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-1",
            title: "Child 1",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-4": {
          id: "note-4",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-1",
            title: "Child 2",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-5": {
          id: "note-5",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-1",
            title: "Child 3",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-6": {
          id: "note-6",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-1",
            title: "Child 4",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-7": {
          id: "note-7",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-2",
            title: "Child 5",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-8": {
          id: "note-8",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-2",
            title: "Child 6",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-9": {
          id: "note-9",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-2",
            title: "Child 7",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-10": {
          id: "note-10",
          children: [
            "note-11",
            "note-12",
            "note-13",
            "note-14",
            "note-15",
            "note-16",
          ],
          hasChildren: true,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "root",
            title: "Parent 3",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-11": {
          id: "note-11",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 8",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-12": {
          id: "note-12",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 9",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-13": {
          id: "note-13",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 10",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-14": {
          id: "note-14",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 11",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-15": {
          id: "note-15",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 12",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
        "note-16": {
          id: "note-16",
          children: [],
          hasChildren: false,
          isExpanded: false,
          data: {
            categoryId: "category-1",
            parentId: "note-10",
            title: "Child 13",
            content: "",
            isTitleFresh: false,
            isContentFresh: false,
          },
        },
      },
    },
  },
};
//
// export const INITIAL_STATE_EMPTY = {
//   notes: {
//     isNoteMovementLoading: false,
//     isNotesLoaded: false,
//     categoryIds: [],
//     byId: {},
//     allIds: [],
//   },
// };
//
// export const INITIAL_STATE = {
//   notes: {
//     isNoteMovementLoading: false,
//     isNotesLoaded: false,
//     categoryIds: [1, 5],
//     allIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
//     byId: {
//       0: {
//         id: 0,
//         sortId: 1,
//         title: "root",
//         content: "root",
//         parentId: undefined,
//         isCategory: true,
//         childPageIds: [1, 4, 5],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       1: {
//         id: 1,
//         sortId: 1,
//         title: "Basic grammar",
//         content: "This is some placeholder content!",
//         parentId: 0,
//         childPageIds: [2, 3],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       2: {
//         id: 2,
//         sortId: 1,
//         title: "Present simple",
//         content: "Try to add some more text if you want to play with it",
//         parentId: 1,
//         childPageIds: [],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       3: {
//         id: 3,
//         sortId: 2,
//         title: "Present continuous",
//         parentId: 1,
//         childPageIds: [6, 7],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       4: {
//         id: 4,
//         sortId: 2,
//         title: "Vocabulary",
//         parentId: 0,
//         childPageIds: [8],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       5: {
//         id: 5,
//         sortId: 3,
//         title: "Russian Basic grammar",
//         content: "In russian there is no basic grammar!",
//         parentId: 0,
//         childPageIds: [],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       6: {
//         id: 6,
//         sortId: 1,
//         title: "Examples",
//         content: "Some examples",
//         parentId: 3,
//         childPageIds: [9],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       7: {
//         id: 7,
//         sortId: 2,
//         title: "Exercises",
//         content: "Some exercises",
//         parentId: 3,
//         childPageIds: [],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       8: {
//         id: 8,
//         sortId: 1,
//         title: "Nice to know words",
//         content: "Words",
//         parentId: 4,
//         childPageIds: [],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       9: {
//         id: 9,
//         sortId: 1,
//         title: "Long explanatory exaple caption",
//         content: "Words",
//         parentId: 6,
//         childPageIds: [10],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//       10: {
//         id: 10,
//         sortId: 1,
//         title: "Long explanatory exaple caption 2",
//         content: "Words",
//         parentId: 9,
//         childPageIds: [],
//         isExpanded: false,
//         isTitleFresh: false,
//         isContentFresh: false,
//       },
//     },
//   },
// };
